{% set version = "0.2.1" %}

package:
  name: utide
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/U/UTide/UTide-{{ version }}.tar.gz
  sha256: fad8625498a58c5753177dc540e00dc513644323d0756952015956cf0b335791

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy

test:
  imports:
     - utide

about:
  home: https://github.com/wesleybowman/UTide
  license: MIT
  license_file: LICENSE.txt
  summary: Python distribution of the MatLab package UTide

extra:
  recipe-maintainers:
    - ocefpaf
    - wesleybowman
