{% set version = "0.2.5" %}

package:
  name: utide
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/U/UTide/UTide-{{ version }}.tar.gz
  sha256: f976ccafdf8392682d5db083b220cdb999b265c9148459f3d7e1a8b8b6e25e47

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy

test:
  imports:
     - utide

about:
  home: https://github.com/wesleybowman/UTide
  license: MIT
  license_file: LICENSE.txt
  summary: Python distribution of the MatLab package UTide

extra:
  recipe-maintainers:
    - ocefpaf
    - wesleybowman
