{% set version = "0.2.6" %}

package:
  name: utide
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/U/UTide/UTide-{{ version }}.tar.gz
  sha256: a49448faefd957521dacfb008f5324d2af516241a52a0c358d3b8d747ba81f66

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools-scm
  run:
    - python >=3.6
    - numpy
    - scipy

test:
  imports:
    - utide
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wesleybowman/UTide
  license: MIT
  license_file: LICENSE.txt
  summary: Python distribution of the MatLab package UTide

extra:
  recipe-maintainers:
    - ocefpaf
    - wesleybowman
