{% set version = "0.2.4" %}

package:
  name: utide
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/U/UTide/UTide-{{ version }}.tar.gz
  sha256: 21999e12ddb8511b92525e3a6e8d5309e5ab92b9f0dc24c666d9f65c734c66a9

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy

test:
  imports:
     - utide

about:
  home: https://github.com/wesleybowman/UTide
  license: MIT
  license_file: LICENSE.txt
  summary: Python distribution of the MatLab package UTide

extra:
  recipe-maintainers:
    - ocefpaf
    - wesleybowman
