travis:
  secure:
    BINSTAR_TOKEN: NMFPS8dyOUM6oyrpqyePihukJ8f75Qu/FoCjbytdiQp2wn1mNYCrQtVvkWPMd7TNzts2xJWIzzj/1QX0o21wnp/eFVYeuOaHmxki1tsg5+kq4lZ2jwv0x8ZsjMsXn3BfgRWYqVZhrHXWile+YT92wGqeiP+Uy6X5jX5NFxm201CWVRItJwFeuqc8Dk+xUrkofWxwEDKEHW3RrjDBKyF+83+pkuW61gfBvEUKkzw+LuW1B67taDLo/dMafDdc6xNMR+IAuak9D8gd924N4HT2n58XzydpOzyXuNHD46zgrvhgpT7X5ma4xp9iF7lltRPQcmoPsDI/ABBAKyLVWBzQ2OH47gHJ7c+RGxl+Xq4PjOr+i7V1PPZmwoSVsnHEjaQf8ZTED31tJwBs08LhqSbEi++c5Q4rNWwFKaC3vweeiH16CGRolrdfR3st0CuU33vhP/3WO1zA4bhEOfcNaH8qH6qLYgXkkTRmfyxoKyHoC1nwB/GJsIQxY9T41Z9IZjG2ZOIXe3NYiHtylvGmQYyq6GSzUPGxyGOD/KkRWY5sJOSDmZIqMPhQy0VEncqUzmw21Gj9e4Z0qIbsmUN+ReiWHh06Y9QEg4we4/xktgi7frSpCM1qf8yOHnkxUnA6jrSIW0Z1jO/PCh4hjGCc7VdFL9FyGm9rmsXw/1/ouRAYO7A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
