travis:
  secure:
    BINSTAR_TOKEN: lI6osWcRsH+R0UcaZoJ5IVsmEgTL5GbxhMoCjvf8Pt/HSXzZ77gofI1QcC7TfvemiMAfZnsrt0znuoIgH6S+mYBtpdpUiV99babgp5Q0xbroWocGt2VXLEsGC3UoBTde7gPtH9FjLQndEkpRkj4c56jEQarM1kVxXxmnTni0Wg1r9z0jneXrRs/FgHfQ1ufXCk0Ht3jJoD8ThEgQKUvMRSw8PUhkvPSVO6vOut0pfvieAExRDIIJaTXl5XW+yHu7zuZSpXOD6JWWFir3rJ4yTKXJ+wR7VMdOS6UPZHXuUyWolGPoBfFBXxMCQsXJbp905HXmdFFikYGTMmsQ+642YNFyQonYUtbg4wlgtDQuEmfdaDUg9ghRBGk95hV7/GESn90FsZBBJXP/RUXbnMzi41yiRzGkr0ywHGqAhXbT8Pu2ifRjAAeHONRFSByIHEBHLPtzp/KWxk8W2FbAP1uzyfXkJx9ihiDUW7WwpwMjqgo9Z6PQjbCzgOPdhsKMCcg5rdp0DJHUHntj2iTYsu5IUG5ReiJdhE5c1AsrPiRxvlY/3co4Wbx+lgVyPD1LzwI2LwcPf0yZrkSDzWX6PUq3LBVhoHRWh08CM1BNaLDyZArUXIboe9w/3Zv+p133F+6mVrAmNUK/ExPu/fAouxZGQ7k9WpO3thQTqyFDrFxHmw0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
